sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  - DOCKER_IMAGE=janerz6/notifications
  - IMAGE_VERSION=0.01

script:
- mvn clean package -U

after_success:
- docker login -u="janerz6" -p=$DOCKER_PASSWORD
- export REPO=$DOCKER_IMAGE:$IMAGE_VERSION
- docker build -t $REPO .
- docker push $REPO